### PR TITLE
Feature repo create file

### PR DESCRIPTION
**Pull request by mipmip**
Hi, just added a new missing api method. Creating files in a repository.

### CODE REVIEW

**Comment by mipmip** [comment]
Oh sorry, missing tests. Will add them.

**Review by icyleaf — APPROVED** [review]

**Review by icyleaf — CHANGES_REQUESTED** [review]
Please fix the CI test pass and the missing tests, thanks

**Comment by mipmip** [comment]
@icyleaf don't know about the nightly crystal build, but I think it's ok. Please check. 

cheers.

**Comment by icyleaf** [comment]
> @icyleaf don't know about the nightly crystal build, but I think it's ok. Please check.
> 
> cheers.

Nightly build uses `master` branch of crystal-lang repo which was some broking changes since [v1.0.0](https://crystal-lang.org/2021/03/22/crystal-1.0-what-to-expect.html), i will fix it.

**Pull request merged**
